### ISSUE TITLE
How does this compare to Anki Quick Adder

### ISSUE THREAD

**Issue by lervag** [patricknaughton01/flash#11]
I'm curious what are the advantages (and dis-advantages) compared to the more mature project [Anki Quick Connect](https://codehealthy.com/chrome-anki-quick-adder/).

**Comment by patricknaughton01** [comment]
I'm not super sure, I haven't used that software before. Just from quickly installing it and playing around for a bit it seems that you still have to copy and paste into the fields? Perhaps there is a shortcut for that that I am not seeing. 

The quick adder seems to be much more fully-featured in terms of formatting options. This software is mostly focused on making it as fast as possible to stick things in your deck. Perhaps I missed it but I'm not sure that the quick adder has automatic translation. I primarily use Anki for foreign language learning so that was important for me to include.

**Comment by lervag** [comment]
No worries.
